### ISSUE TITLE
Wrong Bootstrapping result after addition.

### ISSUE THREAD

**Issue by Umaru-Sagiri** [sp301415/tfhe-go#1]
I write some simple code as below:

    params := tfhe.ParamsUint4.Compile()
    enc := tfhe.NewEncrypter(params)
    defer enc.Free()
    evalKey := enc.GenEvaluationKeyParallel()
    eval := tfhe.NewEvaluater(params, evalKey)
    defer eval.Free()
    a := enc.EncryptLWE(13)
    b := enc.EncryptLWE(7)
    c := eval.AddLWE(a, b)
    fmt.Println(enc.DecryptLWE(c))
    c = eval.Bootstrap(c)
    fmt.Println(enc.DecryptLWE(c))

The output is 4 12.

When the addition result c is larger than the modulus 16, it seems the bootstrap result is always 16-c. May I ask if this is a bug or an inherent result?

**Comment by sp301415** [comment]
Hi, thanks for writing this issue.

Unfortunately, this is an inherent result. You can observe the same behavior in TFHE-rs too.

The reason for this is that Functional Bootstrapping in TFHE is negacyclic. To circumvent this, messages are usually encoded with a bit of padding. However, in this example, the added result is larger than the message modulus, hence overflowing occurs and the padding bit gets sets to 1. This negates the evaluating function, so f(x) = x becomes f(x) = -x. 

Solution to this problem would require implementing FDFB(Full Domain Functional Bootstrapping), which is a part of ongoing research.

Hope this helps!

**Comment by Umaru-Sagiri** [comment]
Thank you very much for your response.

I carefully reviewed your code. Taking Uint4 as an example, it seems that you created a region for Uint5 and implemented modulo 32 additive homomorphism on LWE ciphertexts. During encryption and decryption, you reduce these modulo 32 numbers to Uint4. On the other hand, you uniformly adopted Programmable Bootstrapping, where simple Bootstrapping is treated as an example of {f(x) = x}.

This is a very clever implementation approach. In the Uint5 space, due to the negacyclic property, only 0 to 15 are actually usable. Therefore, you explicitly define the plaintext space as Uint4 to avoid potential errors caused by LUT.

However, I encountered some difficulties when trying to build certain algorithms using your code.
Scenario 1: I tried to construct an algorithm. In the Z16 space, it uses the following NLUT:
0 -> 3
1 -> 2
2 -> 6
3 -> 12
4 -> 10
5 -> 0
6 -> 1
7 -> 11
LUT[8+i] = 16 - LUT[i]
In your design, this process occurs on ParamsUint3. However, due to the properties of modulo 8, the mapping above is reduced to:
0 -> 3
1 -> 2
2 -> 6
3 -> 4
4 -> 6
5 -> 0
6 -> 1
7 -> 5
LUT[8, ..., 15] is the same as before.
At this point, unless ParamsUint5 is used and Bootstrapping is performed after each addition to limit the size of the plaintext, we cannot achieve the above operations in Z16.

Scenario 2: We have arrays A and B of length n, with all elements in Z16. We want to determine for how many i, A[i] = B[i]. This is feasible on ParamsUint4 because A[i], B[i] ∈ [0, 15], A[i] - B[i] ∈ [-15, 15], and only one Programmable Bootstrapping is needed to determine their equality. Subsequently, a simple accumulation is sufficient.
However, if A[i], B[i] undergo previous operations or have undergone Programmable Bootstrapping beforehand, due to the negacyclic property, the comparison mentioned above becomes infeasible on ParamsUint4(A[i] - B[i] may be 16). To solve this problem, we would need to use ParamsUint5 or even ParamsUint6, control the plaintext size through frequent Bootstrapping, and thus complete the computation. This undoubtedly introduces significant overhead.

The commonality in both scenarios is that as the computational circuit grows, we must increase the scale of the plaintext field and perform frequent Bootstrapping to complete the computation. Therefore, I would like to inquire if you have plans to implement multiplication on LWE ciphertext domains as well as naive Bootstrapping (i.e., ParamsUint3 -> Z16, f(x) = x).

Thank you for reading this issue, and look forward to your response.

**Comment by sp301415** [comment]
Thanks for your detailed comment!

In scenario 1, I believe it is possible using `GenLookUpTableFullInPlace` and `LWEDecodeCustom`. `GenLookUpTableFullInPlace` allows to encode f(msg) -> plaintext, rather than f(msg) -> msg, and `LWEDecodeCustom` allows you to decode LWE plaintext with user supplied modulus and delta. 
Here is an example:
```go
params := tfhe.ParamsUint3.Compile()
enc := tfhe.NewEncrypter(params)
defer enc.Free()

eval := tfhe.NewEvaluater(params, enc.GenEvaluationKeyParallel())
defer eval.Free()

// Part of your LUT
f := func(x int) uint64 {
	if x == 7 {
		// You have to scale plaintext manually,
		// Since this function maps message to full encoded plaintext
		return 12 << params.DeltaLog()
	}
	return 0
}

lut := tfhe.NewLookUpTable(params)
eval.GenLookUpTableFullInPlace(f, lut)

ct := enc.EncryptLWE(7)
eval.BootstrapLUTAssign(lut, ct)

// Okay, perhaps I named this method wrong,
// but what this does is decrypt LWE ciphertext to LWE plaintext (undecoded).
ptOut := enc.DecryptLWEPlaintext(ct)
msgOut := enc.DecodeLWECustom(ptOut, 16, params.Delta()) // Force modulus to be 16
fmt.Println(msgOut)
```
This should output 12, as desired.

Scenario 2 is similar to Scenario 1, but for general, non-negacyclic LUT. This is called Full Domain Functional Bootstrapping(FDFB), and is generally really hard. There are few approaches developed, such as [CLOT21](https://eprint.iacr.org/2021/729), [YXS+21](https://eprint.iacr.org/2021/1347). However, most of them requires two bootstrappings, which is computationally similar or even slower than just using larger parameters; CLOT21 is slightly faster than that, but parameter selection is not straightforward IIRC.
What you can do is to keyswitch to larger parameter, but I'm not sure it's better than using a larger parameter from the start.

Hope this helps!
